name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Linux x64
      run: docker build . --file ./EinsTools.ServiceMonitor/Dockerfile --build-arg RUNTIME=linux-x64 --tag service-monitor:linux
    - name: Build the Docker image for Windows x64
      run: docker build . --file ./EinsTools.ServiceMonitor/Dockerfile --build-arg RUNTIME=win-x64 --tag my-image-name:windows
    - name: Build the Docker image for OSX x64
      run: docker build . --file ./EinsTools.ServiceMonitor/Dockerfile --build-arg RUNTIME=osx-x64 --tag my-image-name:osx
      
      
