name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish for Linux x64
        run: dotnet publish -c Release -o ./publish/linux-x64 -r linux-x64 --self-contained true
      - name: Publish for Windows x64
        run: dotnet publish -c Release -o ./publish/win-x64 -r win-x64 --self-contained true  
      - name: Publish for MacOS x64
        run: dotnet publish -c Release -o ./publish/osx-x64 -r osx-x64 --self-contained true
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Archive linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: |
            dist/linux-x64
            !dist/**/*.md
      - name: Archive windows
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: |
            dist/win-x64
            !dist/**/*.md
      - name: Archive macos
        uses: actions/upload-artifact@v4
        with:
          name: osx-x64
          path: |
            dist/osx-x64
            !dist/**/*.md
      
      
